### NumPy Ecosystem

1. statsmodel
2. scikit-image
3. scikit-learn
4. pandas
5. matplotlib


In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
array_one = np.array([0, 1, 3, 5, 7, 9])

In [6]:
array_one

array([0, 1, 3, 5, 7, 9])

In [7]:
num = [11, 22, 33, 44, 55, 66, 77]
array_two = np.array(num)

array_two

array([11, 22, 33, 44, 55, 66, 77])

### zeros((n, m)) function

creates an array with zero values and a size of (n, m)
default data type - float

### ones((n, m)) function

creates an array with 1 value and a size of (n, m)
default data type - float

### empty((n, m)) function

creates an array with empty values and a size of (n, m)

In [8]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
array_of_ones = np.ones((3,2), dtype=np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [13]:
array_empty = np.empty((4,7))
array_empty

array([[1.03212452e-311, 1.03208776e-311, 3.10422585e+169,
        7.20100765e+252, 2.21057010e+161, 7.62870734e+228,
        6.62901773e+265],
       [2.16209963e+233, 3.18892178e-110, 5.12693495e-116,
        2.95776535e+203, 5.71446009e-307, 1.03212446e-311,
        1.03208500e-311],
       [1.86170188e+243, 8.24227379e-072, 2.58437852e+185,
        4.83245960e+276, 2.92298185e+222, 8.54795557e+141,
        1.99255405e-311],
       [5.71425971e-307, 1.03212498e-311, 1.03208772e-311,
        4.34728362e-320, 2.60860094e-138, 0.00000000e+000,
        2.68955553e-317]])

### eye(n) function

creates a square array with size n
diagonal values are 1; all other values are 0

### arange(x, y, i) function

creates a one-dimensional array with values x (lower bound) to y (upper bound, exclusive) with i interval

### reshape(n, m) function
converts an array to a specified size (n, m)

### ones_like(array) function
creates a new array with 1 values which shape is the same as that of the array argument

In [14]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
array_of_evens = np.arange(2, 24, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [19]:
array_2D = np.array([[3,4,6],[2,1,6]])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [17]:
array_2D.shape

(2, 3)

In [21]:
array_nd = np.arange(1,11).reshape(2,5)
array_nd

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
array_ones = np.ones_like(array_nd)

In [23]:
array_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])