In [1]:
import numpy as np

In [2]:
p = np.array([9, 8, 7])
q = np.array([3, 2, 4])

### Basic Operations

**Same-sized arrays performs +, -, * and / in an element by element manner.**

**Boolean operations return an array evaluating each element in the array.**

In [3]:
p + q

array([12, 10, 11])

In [4]:
p - q

array([6, 6, 3])

In [5]:
p * q

array([27, 16, 28])

In [6]:
p / q

array([3.  , 4.  , 1.75])

In [7]:
p % 2

array([1, 0, 1], dtype=int32)

In [8]:
p > 8

array([ True, False, False])

In [9]:
x = np.array([[2,1], [1,3]])
y = np.array([[3,2], [4,2]])

In [10]:
x + y

array([[5, 3],
       [5, 5]])

In [11]:
x * y

array([[6, 2],
       [4, 6]])

In [12]:
x.dot(y)

array([[10,  6],
       [15,  8]])

In [13]:
np.dot(x,y)

array([[10,  6],
       [15,  8]])

In [14]:
x *= 4

In [15]:
print(x)

[[ 8  4]
 [ 4 12]]


### Aggregate Operations

In [16]:
fleet_mileage = np.array([14130, 37234, 21892, 11479, 6890, 27981])

In [17]:
fleet_mileage.sum()

119606

In [18]:
fleet_mileage.min()

6890

In [19]:
fleet_mileage.max()

37234

In [20]:
fleet_mileage.mean()

19934.333333333332

In [21]:
num = np.arange(16).reshape(4,4)

In [22]:
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
num.sum()

120

In [25]:
num[0].sum()

6

In [26]:
#returns the sum of each column
num.sum(axis=0)

array([24, 28, 32, 36])

In [27]:
#returns the sum of each row
num.sum(axis=1)

array([ 6, 22, 38, 54])

In [28]:
#returns the average of each row
num.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])