In [1]:
import numpy as np

In [2]:
circle_radii = np.array([145, 120, 90, 60, 45, 30])

In [4]:
circle_diameters = circle_radii * 2

circle_diameters

array([290, 240, 180, 120,  90,  60])

In [6]:
circle_areas = np.pi * circle_radii * 2

circle_areas

array([911.06186954, 753.98223686, 565.48667765, 376.99111843,
       282.74333882, 188.49555922])

In [7]:
angle_degrees = np.array([0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360])

In [8]:
angle_radians = angle_degrees * np.pi / 180

angle_radians

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653, 6.28318531])

In [10]:
np.sin(angle_radians)

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  5.00000000e-01,  1.22464680e-16, -5.00000000e-01,
       -8.66025404e-01, -1.00000000e+00, -8.66025404e-01, -5.00000000e-01,
       -2.44929360e-16])

In [11]:
np.arcsin(np.sin(angle_radians))

array([ 0.00000000e+00,  5.23598776e-01,  1.04719755e+00,  1.57079633e+00,
        1.04719755e+00,  5.23598776e-01,  1.22464680e-16, -5.23598776e-01,
       -1.04719755e+00, -1.57079633e+00, -1.04719755e+00, -5.23598776e-01,
       -2.44929360e-16])

In [12]:
x = np.arange(4, 31, 5)

x

array([ 4,  9, 14, 19, 24, 29])

In [14]:
#e to the power of x
expo = np.exp(x)

expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

In [16]:
sqrt = np.sqrt(x)
sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

In [17]:
np.median(x)

16.5

In [21]:
float_values = np.genfromtxt('datasets/float_values.csv', delimiter=',')

In [22]:
float_values

array([0.26037059, 0.90514556, 0.53929637, ..., 0.90960463, 0.08013759,
       0.17109204])

In [23]:
float_values.shape

(5999,)

In [24]:
np.mean(float_values)

0.48848748467464576

In [25]:
np.std(float_values)

0.2891852572545287