In [1]:
import numpy as np

Create an array x of the same shape as another array y with all elements set to 1

In [2]:
y = np.arange(16).reshape(2,8)

In [3]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [4]:
x = np.ones_like(y)

In [5]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

Last 20 rows and columns 2-5 of an array

In [9]:
array_2D = np.arange(200).reshape(40,5)
array_2D

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 1

In [20]:
array_2D[-20:, 1:6]

array([[101, 102, 103, 104],
       [106, 107, 108, 109],
       [111, 112, 113, 114],
       [116, 117, 118, 119],
       [121, 122, 123, 124],
       [126, 127, 128, 129],
       [131, 132, 133, 134],
       [136, 137, 138, 139],
       [141, 142, 143, 144],
       [146, 147, 148, 149],
       [151, 152, 153, 154],
       [156, 157, 158, 159],
       [161, 162, 163, 164],
       [166, 167, 168, 169],
       [171, 172, 173, 174],
       [176, 177, 178, 179],
       [181, 182, 183, 184],
       [186, 187, 188, 189],
       [191, 192, 193, 194],
       [196, 197, 198, 199]])

Reshape an array to 4 columns

In [16]:
def reshape_four_columns(array):
    array = array.reshape(-1, 4)
    
    print(array)
    return array

In [18]:
my_array = np.arange(24).reshape(3,8)

my_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [19]:
reshape_four_columns(my_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])